pr:
  branches:
    include:
      - master
  paths:
    include:
      - Husa.Extensions.ServiceBus

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Husa.Extensions.ServiceBus

pool:
  vmImage: windows-latest

variables:
  isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudHomesUSA'
    organization: 'homesusa'
    scannerMode: 'MSBuild'
    projectKey: 'Husa_Extensions.ServiceBus'
    projectName: 'Husa.Extensions.ServiceBus'
    extraProperties: |
      sonar.exclusions=**/obj/**,**/*.dll
      sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)/**/coverage.opencover.xml
      sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/Husa.Extensions.ServiceBus.csproj'
    restoreArguments: '/property:Configuration=Release'
    feedsToUse: 'select'
    vstsFeed: 'f820f957-6781-4cd6-b5f5-e720c189507f/891ce0ed-37b7-4336-b1fe-079c0525a171'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/Husa.Extensions.ServiceBus.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: DotNetCoreCLI@2
  condition: ne(variables.isPullRequest, true)
  inputs:
    command: 'pack'
    packagesToPack: '**/Husa.Extensions.ServiceBus.csproj'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
  condition: and(succeededOrFailed(), ne(variables.isPullRequest, true))
