pr:
  branches:
    include:
      - master
  paths:
    include:
      - Husa.Extensions.Domain

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Husa.Extensions.Domain

pool:
  vmImage: windows-latest

variables:
- group: homesusa.husa.extensions.global
- name: isPullRequest
  value: $[eq(variables['Build.Reason'], 'PullRequest')]

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudHomesUSA'
    organization: 'homesusa'
    scannerMode: 'MSBuild'
    projectKey: 'Husa_Extensions.Domain'
    projectName: 'Husa.Extensions.Domain'
    extraProperties: |
      sonar.exclusions=**/obj/**,**/*.dll
      sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)/**/coverage.opencover.xml
      sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx
- task: NuGetAuthenticate@1
  inputs:
   forceReinstallCredentialProvider: true
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/Husa.Extensions.Domain.csproj'
    restoreArguments: '/property:Configuration=$(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/Husa.Extensions.Domain.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: DotNetCoreCLI@2
  condition: ne(variables.isPullRequest, true)
  inputs:
    command: 'pack'
    packagesToPack: '**/Husa.Extensions.Domain.csproj'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
  condition: and(succeededOrFailed(), ne(variables.isPullRequest, true))
