trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Husa.Extensions.Common

pool:
  vmImage: windows-latest

variables:
  isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/Husa.Extensions.Common.csproj'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/Husa.Extensions.Common.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  condition: ne(variables.isPullRequest, true)
  inputs:
    command: 'pack'
    packagesToPack: '**/Husa.Extensions.Common.csproj'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
  condition: and(succeededOrFailed(), ne(variables.isPullRequest, true))
