namespace Husa.Extensions.Downloader.Trestle.Models.Enums
{
    public enum CurrentFinancing
    {
        Assumable,
        CalVetLoan,
        Cash,
        Contract,
        Conventional,
        ExistingBonds,
        FannieMae,
        Fha,
        Fha203b,
        Fha203k,
        FreddieMac,
        GovernmentLoan,
        LeasedRenewables,
        None,
        Other,
        PowerPurchaseAgreement,
        Private,
        PropertyAssessedCleanEnergy,
        SeeRemarks,
        TrustDeed,
        Usda,
        Va,
        VaNoLoan,
        VaNoNoLoan,
    }
}
