namespace Husa.Extensions.Downloader.Trestle.Models.Enums
{
    public enum ExistingLeaseType
    {
        AbsoluteNet,
        BaseAndPercentage,
        CpiAdjustment,
        DepositRequired,
        EscalationClause,
        Fixed,
        FullService,
        Gross,
        GroundLease,
        IndustrialGross,
        Modified,
        ModifiedGross,
        Net,
        Nn,
        Nnn,
        None,
        NotForLease,
        Oral,
        Other,
        Percentage,
        SeeAgent,
        SeeRemarks,
        Sublease,
    }
}
