namespace Husa.Extensions.Downloader.Trestle.Models.Enums
{
    public enum LeaseTerm
    {
        Daily,
        FiveYears,
        FourYears,
        LessThan1Year,
        LongTerm,
        MonthToMonth,
        Negotiable,
        NineMonths,
        None,
        Other,
        OverSixYears,
        RenewalOption,
        Seasonal,
        SeeRemarks,
        ShortTermLease,
        SixMonths,
        Sublease,
        ThirtySixMonths,
        ThreeMonths,
        ThreeToFiveYears,
        TwelveMonths,
        TwentyFourMonths,
        Weekly,
    }
}
