namespace Husa.Extensions.Downloader.Trestle.Models.Enums
{
    public enum MemberType
    {
        Affiliate,
        Assistant,
        AssociateBroker,
        AssociationStaff,
        Broker,
        BrokerOfRecord,
        DesignatedRealtorAppraiser,
        DesignatedRealtorParticipant,
        LicensedAssistant,
        MlsOnlyAppraiser,
        MlsOnlyBroker,
        MlsOnlyBrokerAssociate,
        MlsOnlySalesperson,
        MlsStaff,
        NonMemberVendor,
        OfficeManager,
        OfficeStaff,
        Photographer,
        RealtorAppraiser,
        RealtorBrokerAssociate,
        RealtorSalesperson,
        Team,
        UnlicensedAssistant,
    }
}
