namespace Husa.Extensions.Downloader.Trestle.Models.Enums
{
    public enum MemberType
    {
        Affiliate,
        Assistant,
        AssociateBroker,
        AssociationStaff,
        Broker,
        BrokerOfRecord,
        DesignatedREALTORAppraiser,
        DesignatedREALTORParticipant,
        LicensedAssistant,
        MLSOnlyAppraiser,
        MLSOnlyBroker,
        MLSOnlyBrokerAssociate,
        MLSOnlySalesperson,
        MLSStaff,
        NonMemberVendor,
        OfficeManager,
        OfficeStaff,
        Photographer,
        REALTORAppraiser,
        REALTORBrokerAssociate,
        REALTORSalesperson,
        Team,
        UnlicensedAssistant,
    }
}
