namespace Husa.Extensions.Downloader.Trestle.Models.Enums
{
    public enum PropertyCondition
    {
        AdditionsAlterations,
        AverageCondition,
        BelowAverage,
        BuildingPermit,
        Excellent,
        Fixer,
        GoodCondition,
        KnownDamage,
        NeverOccupied,
        NewConstruction,
        Other,
        PoorCondition,
        RepairsCosmetic,
        RepairsMajor,
        Resale,
        SeeDisclosure,
        SeeRemarks,
        ShowsWell,
        TearDownValueInLand,
        TermiteClearance,
        ToBeBuilt,
        Turnkey,
        UnderConstruction,
        UnderRenovation,
        Unknown,
        UpdatedRemodeled,
        VeryGoodCondition,
    }
}
