namespace Husa.Extensions.Downloader.Trestle.Models.Enums
{
    public enum SpaFeatures
    {
        AboveGround,
        Association,
        Bath,
        Community,
        Conventional,
        ElectricHeat,
        Fiberglass,
        GasHeat,
        Gunite,
        Heated,
        HotTub,
        IndoorHotTub,
        InGround,
        None,
        NoPermits,
        OutdoorHotTub,
        Permits,
        Private,
        RoofTop,
        Sauna,
        Screened,
        SeeRemarks,
        SolarHeat,
        SteamRoom,
    }
}
