namespace Husa.Extensions.Downloader.Trestle.Models.Enums
{
    public enum WaterHeater
    {
        Central,
        Coal,
        Common,
        Electric,
        EnergyStarQualified,
        Gas,
        Geothermal,
        HeatPump,
        HighEfficiency,
        Hybrid,
        InstantHotWater,
        Insulated,
        Leased,
        Multiple,
        None,
        OffHeatingSystem,
        Oil,
        Other,
        Owned,
        Propane,
        Recirculating,
        SeeRemarks,
        Solar,
        Tankless,
        Wood,
    }
}
